[tools]
bat = "latest"
docker-cli = "latest"
fzf = "latest"
lazygit = "latest"
lsd = "latest"
lua = "latest"
neovim = "latest"
node = "latest"
rclone = "latest"
ripgrep = "latest"
starship = "latest"
tlrc = "latest"
tmux = "latest"
tree-sitter = "latest"
yazi = "latest"
zoxide = "latest"
